---
title: "Materials for the EEID Workshop 2026"
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
    css: styles.css
---

# Pre-work and set-up

## Software

- We will be using [`R`](https://cran.r-project.org/) for all data manipulation and analyses/model fitting. Any operating system (Windows, Mac, Linux) will do, as long as you have `R` (version 3.6 or higher) installed.

- We will be using [`RStudio`](https://www.rstudio.com/) to run R. 

- We will host all materials on [GitHub](https://github.com/). All students need a GitHub account as that is how we will share materials.

## Pre-requisites

For this workshop, we assume basic familiarity with:

-   Basic [`R` Programming Language](https://cran.r-project.org/)
-   Basic calculus including functions
-   Basic probability and statistics 

***Review of `R`***

1. A great short refresher on R is the [Biological Computing in R Chapter](https://mulquabio.github.io/MQB/notebooks/r.html) in [The Multilingual Quantitative Biologist](https://mulquabio.github.io/MQB/intro.html).

2.  Some resources for brushing up on R:
- [The Multilingual Quantitative Biologist](https://mulquabio.github.io/MQB/intro.html)
- [Code Academy](https://www.codecademy.com/learn/learn-r) 
- [Data quest](https://www.dataquest.io/blog/learn-r-for-data-science/)

***Review of Calculus***

1. There are many on-line tutorials. One resources with some good videos is
 [3blue1brown](https://www.3blue1brown.com/?topic=calculus).

2. A concise cheatsheet summary can be found under `A Complete Calculus Cheatsheet' at [Paul's Online Notes](https://tutorial.math.lamar.edu/extras/cheatsheets_tables.aspx)

***Review of Probability and Statistics***

There are many on-line tutorials. One resources with some good videos is
 [3blue1brown](https://www.3blue1brown.com/?topic=probability).


<br> <br>

# Live Workshop Materials

## Introduction to the Workshop

-   [Lecture Slides](blank.qmd)

<br> <br>

## Introduction to GitHub through R

-   [Lecture Slides](blank.qmd)

<br> <br>

## Introduction Infectious Disease Modeling

-   [Lecture Slides](blank.qmd)
<br> <br>

## Basic Data Fitting

-   [Lecture Slides](blank.qmd)
<br> <br>

## Introduction to Spatial Modeling

-   [Lecture Slides](blank.qmd)
<br> <br>


